# Generated by Django 5.1.3 on 2024-12-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinventory',
            name='cars_count',
            field=models.IntegerField(),
        ),
    ]
